# -*- coding: utf-8 -*-
"""matplotlib_tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qg4lGX7ySPI5oFyttuNgcOP7wHgmIte_
"""

import numpy as np
import matplotlib.pyplot as plt
#plt.style.use('seaborn')

x = np.random.randint(200,size=(300))
y = np.random.randint(200,size=(300))
print(x)
cl = np.random.randint(300,size=(300))
size = 5 * np.random.randint(200,size=(300))
plt.scatter(x,y,c=cl,cmap='nipy_spectral',s=size,alpha=0.5)

#simply plotting x and y as a straight line
x = np.arange(10) #2-> start, 10-> stop, 1->step
print(x)
y = np.arange(10)
plt.plot(x,y,'*')
plt.show

#to plot only the pointss in the plt.plot section we use another parameter 'o' which will display only the point as 'o'
plt.plot(x,y,'o')

#if we donot specify x axis it will automatically take values from 0 upto the length of y
y = np.array([2,5,8,1])
plt.plot(y)
plt.show()

#we can use marker to define the points, ms(marker_size) to define the size of marker
plt.plot(y,marker = 'o',ms=60,mec = 'r')
plt.show()

plt.plot(y,'*--r',ms = 40,) # '*' denotes every point '-- denotes the line design, it can be also :,-,._, and 'g' denotes green color, it can be red'
#mec = markeredgecolor

plt.plot(x,y)
font1 = {'family':'serif','color':'blue','size':20}
font2 = {'family':'serif','color':'darkred','size':20}
plt.xlabel('weight',fontdict = font1) #fontdict is used to change the font of the labels
plt.ylabel('height',fontdict = font2)
plt.title("OBESE GRAPH",fontdict = font1) #loc is used to determine the location of the title, it can be left or right

plt.plot(x,y)
plt.grid(axis='y',linestyle = '--', linewidth =1, color = 'black') #defining the grid only for the x axis

import numpy as np
import matplotlib.pyplot as plt
a = np.array([1,2,3,4])
b = np.array([2,5,6,7])
plt.subplot(1,4,1) #plotting many lines in one area (1,2,1) 1 indicates there will be 1 row, 2 indicates there will be 2 cols of graph and 1 indicates this is the 1st subgraph
plt.plot(a,b)
plt.xlabel('day')
plt.ylabel('night')
x = np.arange(8)
y = np.arange(8,16)
plt.subplot(1,4,2)
plt.plot(x,y)

x_a = np.arange(8)
y_b = np.random.randint(23,78,size=8)
plt.subplot(1,4,3)
plt.xlabel('asdf')
plt.ylabel('sadhfjkh')
plt.plot(x_a,y_b)

x_a1 = np.arange(8)
y_b1 = np.random.randint(23,78,size=8)
plt.subplot(1,4,4)
plt.xlabel('asdf')
plt.ylabel('sadhfjkh')
plt.plot(x_a1,y_b1)

plt.suptitle('DEMO') #suptitle gives the overall title of all graph

a = np.array(["red","green","blue","yellow","pink","black","orange","purple","beige","brown"])
fig, ax = plt.subplots(2,figsize = (10,6))

plt.scatter(x,y,color=a)
plt.show()

import numpy as np
a = np.random.randint(100,size=100)
a

import matplotlib.pyplot as plt
import numpy as np
e = np.random.randint(100,size=(100))
print(e)
f = np.random.randint(100,size=(100))
sz = 10 * np.random.randint(99,size=(100))
sk = 10
print(sz)
colors = np.arange(100)
plt.scatter(e,f,s = sk, c = colors, alpha =0.5 ,cmap = 'nipy_spectral' ) #alpha-> transparency of bubbles
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.random.randint(100, size=(100))
y = np.random.randint(100, size=(100))
colors = np.random.randint(100, size=(100))
sizes = 10* np.random.randint(100, size=(100)) #here 10*np indicates that the size is increased by 10 times then the original

plt.scatter(x, y, c=colors, s=sizes, alpha=0.5, cmap='nipy_spectral')

plt.colorbar().set_label('intensity')

plt.show()

#bars in matplot

x = np.random.rand(20)
y = np.random.rand(20)
cl = np.random.rand(20)
sz = np.arange(40,60)
print(sz)
plt.scatter(x,y,s=100,c=cl,cmap='Greens',marker='o',edgecolor = 'y',linewidth = 1,alpha=0.75) #alpha is the transparency
cbar = plt.colorbar()
cbar.set_label('satisfaction level')

import pandas as pd
df = pd.read_csv("bmw.csv")
df





ml = df['mileage']
ep = df['engine_power']
p = df['price']

plt.scatter(ml,ep,marker="o",s=50,c = p,cmap="summer")

import numpy as np
from matplotlib import pyplot as plt

plt.rcParams["figure.figsize"] = [7.50, 3.50]
plt.rcParams["figure.autolayout"] = True

N = 50
x = np.random.randn(N)
y = np.random.randn(N)

plt.scatter(x, y, c=y, cmap="RdPu") #c sets different 50(N) colors for different x,y points, cmaps defines the ranges
y = plt.colorbar()
y.set_label('intensity')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

x = np.random.rand(50)
y = np.random.rand(50)

plt.scatter(x, y, color='red', marker='o', label='Random Data')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Scatter Plot with plt.scatter')
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x = np.random.randint(100,size=50)
y = np.random.randint(100,size=50)
sz = 10 * np.random.randint(100,size=50)
plt.scatter(x,y,alpha=0.4, cmap = 'nipy_spectral')
plt.show()

plt.colorbar().set_label('intensity')

import numpy as np
import matplotlib.pyplot as plt
a = np.arange(2,5,0.2)
print(a)
plt.plot(a,a**2,'r--',a*2,a**3,'bs',2)

import numpy as np
import matplotlib.pyplot as plt

x = np.random.randint(10,50000,250)
y = np.random.randint(10,50000,250)

plt.subplot(2,3,1)
plt.xlabel("height",fontstyle = "italic",fontsize=14)
plt.ylabel("weight",fontstyle = "italic",fontsize=14)
plt.scatter(x,y,c="r")
plt.title("January")

x_1 = np.random.randint(10,50000,250)
y_1 = np.random.randint(10,50000,250)

plt.subplot(2,3,2)
plt.xlabel("height",fontsize=8)
plt.ylabel("weight",fontstyle = "italic",fontsize=6)
plt.scatter(x_1,y_1)
plt.title("February")

